[dependencies]
base = "0.11.2"
promtracker = "0.5.3"
vector = "0.3.1"
token_handler = "https://github.com/research-ag/token-handler#de156ef0bc3cd85ac29c8e1104104022d7f2719f"
token_handler_legacy = "https://github.com/research-ag/token-handler#644b37126dd5f6bcc09193bec86272e18f26b297"
mrr = "https://github.com/research-ag/motoko-lib#main"
auction = "https://github.com/research-ag/auction#rc-0.0.1-5"
icrc84 = "https://github.com/research-ag/icrc-84#750573596a0f31780bf0caaab1cd247832a0b0f5"

[toolchain]
moc = "0.11.2"
